services:

  child-protect-game:
    image: nginx:alpine
    container_name: child-protect
    ports:
      - 8008:80
    volumes:
      - ./child_game_server/html/:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf.ro
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    env_file:
      - .env
    container_name: cloudflare-tunnel-child
    restart: always
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    depends_on:
      - child-protect-game
